In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import EarlyStopping

In [ ]:
file = "Tortise.csv"
df = pd.read_csv(file)

In [ ]:
print(df)

     Nest_Number  Elevation  AvgTemp   Latitude  Longitude  Strike  Washovers
0              1      2.005     28.13  31.78893  -81.05676    28.0          0
1              2      2.676     29.38  31.80665  -81.04015     1.0          0
2              3      2.088     29.21  31.82410  -81.04753    28.0          0
3              4      1.853     29.33  31.77467  -81.06917    22.0          0
4              5      2.806     29.67  31.78591  -81.05904    76.0          0
..           ...        ...       ...       ...        ...     ...        ...
165          193        NaN     31.14  31.81445  -81.03735    24.0          0
166          195        NaN     30.71  31.79482  -81.05193    53.0          0
167          196        NaN     30.39  31.82235  -81.04929   228.0          1
168          199        NaN     30.08  31.72737  -81.12714   220.0          6
169          200        NaN     30.53  31.75788  -81.08699    50.0          3

[170 rows x 7 columns]


In [ ]:
Y = df['Nest_Number']
X = df.drop(['Nest_Number'], axis=1)

print(X.shape)
print(Y.shape)

X = np.array(X)

(170, 6)
(170,)


In [ ]:
Y.head()

0    1
1    2
2    3
3    4
4    5
Name: Nest_Number, dtype: int64

In [ ]:
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
dummy_y = np_utils.to_categorical(encoded_Y)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169]
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [ ]:
# build a model
model = Sequential()
model.add(Dense(16, input_shape=(X.shape[1],), activation='relu'))
model.add(Dense(170, activation='softmax'))
model.summary()

# compile the model
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 16)                112       
                                                                 
 dense_5 (Dense)             (None, 170)               2890      
                                                                 
Total params: 3,002
Trainable params: 3,002
Non-trainable params: 0
_________________________________________________________________


In [ ]:
import keras
from keras.callbacks import EarlyStopping

es = keras.callbacks.EarlyStopping(monitor='val_loss',
                                   mode='min',
                                   patience=10,
                                   restore_best_weights=True) # important - otherwise you just return the last weigths...

# now we just update our model fit call
history = model.fit(X,
                    dummy_y,
                    callbacks=[es],
                    epochs=5, # you can set this to a big number!
                    batch_size=10,
                    shuffle=True,
                    validation_split=0.2,
                    verbose=1)

Epoch 1/5
14/14 [==============================] - 1s 17ms/step - loss: nan - accuracy: 0.0074 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 2/5
14/14 [==============================] - 0s 5ms/step - loss: nan - accuracy: 0.0074 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 3/5
14/14 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.0074 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 4/5
14/14 [==============================] - 0s 5ms/step - loss: nan - accuracy: 0.0074 - val_loss: nan - val_accuracy: 0.0000e+00
Epoch 5/5
14/14 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.0074 - val_loss: nan - val_accuracy: 0.0000e+00
